# rate
ctrl_rate: 1000.0
rate_state: 500.0

# robot connection
robot_host: "192.168.1.100"
robot_port: 8439

# frame id
robot_frame_id: "base_link"

# driver state buffer size
state_buffer_size: 200

# sensor timestamp enable
sens_ts: false

# time source: false → PTP (ns_now), true → ROS clock
use_ros_time: false

# KCP transport
enable_kcp: true

